# Generated by Django 2.2.6 on 2019-11-04 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('clues_count', models.IntegerField()),
            ],
        ),
    ]
